# Generated by Django 5.2.6 on 2025-09-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoResume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='users',
            new_name='user',
        ),
    ]
